### ISSUE TITLE
Cinema 4D freezes when loading a model

### ISSUE THREAD

**Issue by roket333** [xNWP/Cinema-4D-Source-Tools#1] opened 2018-04-09 18:47 UTC
when i try to load a model, Cinema 4D just freezes and i need to use Task Manager to kill it

**Comment by xNWP** [comment] 2018-04-09 19:08
Hi roket, sorry to hear about this, can you please supply the following information so that I may look into it.

- Cinema 4D Version
- Source Tools Version
- Crowbar Version (if the model was decompiled with crowbar)
- Model name and source (or a link to download the model itself)

**Comment by roket333** [comment] 2018-04-09 19:15
Cinema 4D R19.024
Source Tools 0.40
Crowbar 0.42.0.0
Model is the stock Sniper Rifle from Team Fortress 2, from tf2_misc_dir.vpk in the tf folder

ive tried some other models from other games like Black Mesa and SFM, but the same issue happens

**Comment by xNWP** [comment] 2018-04-09 19:34
Well, the problem is likely that Crowbar is not updated, try decompiling the model(s) with the latest version of crowbar -- 0.56 https://steamcommunity.com/groups/CrowbarTool -- I don't have tf2 downloaded at the moment, if that works please let me know, if it doesn't could you possibly send me the model?

**Comment by roket333** [comment] 2018-04-09 19:42
sure, ill give that a try

**Comment by roket333** [comment] 2018-04-09 19:51
decompiled it with the latest Crowbar, but Cinema 4D still freezes
here's the mdl and other parts
[c_sniperrifle.zip](https://github.com/xNWP/Cinema-4D-Source-Tools/files/1891528/c_sniperrifle.zip)

**Comment by xNWP** [comment] 2018-04-09 19:55
Okay, I'm actually leaving for a bit today but I'll look into this later, I'll hopefully find the cause sometime in the next 12 hours.

**Comment by xNWP** [comment] 2018-04-10 06:28
This has been fixed in 0.41-alpha, thanks for helping me find the problem!
https://github.com/xNWP/Cinema-4D-Source-Tools/releases/tag/0.41-alpha

**Closed** 2018-04-10 06:28 UTC
Labels: bug
