### ISSUE TITLE
How to open the cdl64 file of cinema4d for editing

### ISSUE THREAD

**Issue by Mixiaxiaoyu** [xNWP/Cinema-4D-Source-Tools#9] opened 2019-11-04 15:17 UTC
I want to open a cinema 4d cdl64 file because I want to translate some of the text myself!

**Comment by xNWP** [comment] 2019-11-04 19:03
Hi @Mixiaxiaoyu ,

To translate the plugin you can do this by translating all the text in the "string tables". These are located under the res/string_us folder and have a `.str` suffix, they can be opened by any text editor. Make a duplicate of the folder and change the country code (us is the default) to the country of your choosing (here's a utility for finding your country code: https://www.iso.org/obp/ui/#search/code/). So for example, translating to Russian would mean you create a folder called `strings_ru`. Any string entries that have the comment `DNT` means "Do Not Translate".

If you wanted to release this translation (or have it included officially in later releases), you might want to wait for some time as I  am actually completely rewriting the plugin for the latest version of Cinema 4D (how long this will take is going to depend on my school schedule unfortunately). So all current strings will not be used in future releases.

**Closed by xNWP** 2019-11-04 19:03 UTC
Labels: question
